#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH --mem=64G
#SBATCH -t 30:00:00
#SBATCH -J eggnog_annotation
#SBATCH --mail-user=marzieh.rahnama86@gmail.com
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=/home/marziehh/Genom-Analysis/out/eggnog_annotation_%j.out
#SBATCH --error=/home/marziehh/Genom-Analysis/out/eggnog_annotation_%j.err

module load bioinfo-tools
module load eggNOG-mapper/2.1.9

INPUT_BASE=/home/marziehh/Genom-Analysis/results/annotation
OUTPUT_BASE=/proj/uppmax2025-3-3/GA_marziehh/eggnog_results

for strain in r7 hp126; do
    echo "Processing $strain"

    INPUT_DIR="${INPUT_BASE}/prokka_${strain}"
    OUTPUT_DIR="${OUTPUT_BASE}/${strain}_diamond"
    mkdir -p "$OUTPUT_DIR"

    FAA_FILE="${INPUT_DIR}/${strain}_annotation.faa"
    CLEAN_GFF_FILE="${INPUT_DIR}/${strain}_annotation_clean.gff"

    if [[ -f "$FAA_FILE" && -f "$CLEAN_GFF_FILE" ]]; then
        emapper.py \
            -i "$FAA_FILE" \
            --itype proteins \
            -m diamond \
            --cpu 16 \
            -o ${strain}_eggnog_results \
            --output_dir "$OUTPUT_DIR" \
            --decorate_gff "$CLEAN_GFF_FILE" \
            --decorate_gff_ID_field ID \
            --tax_scope bacteria \
            --excel \
            --override

        echo "Annotation completed for $strain"
    else
        echo "Missing input for $strain"
    fi
done

echo "All annotations done at $(date)"

