#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J fastqc_raw_dna_long
#SBATCH --mail-type=ALL
#SBATCH --mail-user=Marzieh.rahnama86@gmail.com
#SBATCH --output=/home/marziehh/Genom-Analysis/out/fastqc_raw_dna_long_%j.out

# Load required modules
module load bioinfo-tools FastQC

# Move to working directory
cd /home/marziehh/Genom-Analysis/

# --- Configuration ---
RAW_DIR="data/dna"
FASTQC_DIR="results/fastqc/dna_long_read_raw"
SRR_LONG_IDS=("SRR24413066" "SRR24413072")  # hp126 and r7

# --- Setup ---
set -e

mkdir -p ${FASTQC_DIR}/hp126
mkdir -p ${FASTQC_DIR}/r7

# --- Function to run FastQC on samples ---
for srr_id in "${SRR_LONG_IDS[@]}"; do
    if [[ $srr_id == "SRR24413066" ]]; then
        strain="hp126"
    else
        strain="r7"
    fi

    fastqc ${RAW_DIR}/${strain}/long_read/${srr_id}.fastq.gz -o ${FASTQC_DIR}/${strain}/

    echo "Finished FastQC for ${srr_id} (long reads)"
done

echo "FastQC for raw DNA long reads completed."
